-- Baseline schema — captured 2026-09-12
--
-- Audit finding D1 (docs/PROJECT_AUDIT_2026-09.md).
--
-- ============================================================================
-- WHY THIS EXISTS
-- ============================================================================
-- `scripts/sql/` contained migrations for `ceb_bill_ingestions` and
-- `ceb_bill_extractions` but for none of the tables the dashboard actually reads. The shape
-- of `ceb_data`, `inverter_data_daily_summary`, `system_settings` and the rest lived only
-- inside Supabase — so the schema of the core data model was unrecoverable from the repo.
--
-- This is a point-in-time reconstruction, generated from the live database
-- (information_schema + pg_indexes), not written from memory. It is a BASELINE, not a
-- migration: everything is `if not exists`, so running it against the existing project is a
-- no-op. Its job is to let the schema be rebuilt from scratch, reviewed in a diff, and
-- version-controlled from here on.
--
-- RLS policies are deliberately NOT included — see
-- 2026-09-12_revoke_anon_writes.sql for the current policy state and the reasoning.
--
-- Future schema changes should get their own dated migration file rather than editing this.
-- ============================================================================

-- ---------------------------------------------------------------- ceb_data
-- Canonical CEB billing table. Every earnings figure on the dashboard derives from it.
create table if not exists public.ceb_data (
  id bigint generated by default as identity primary key,
  bill_date date not null,
  earnings numeric,
  meter_reading numeric default 0,
  units_exported numeric default 0,
  created_at timestamp without time zone default now(),
  bill_image_path text,
  billing_period_start date,
  billing_period_end date,
  data_source text default 'manual_entry'::text,
  file_path text,
  ingestion_id uuid,
  account_number text,
  billing_month text
);

-- Backs the `onConflict: 'account_number, billing_month'` upsert used by the approve and
-- manual-entry paths. Without it, re-approving a bill would duplicate the month.
create unique index if not exists ceb_data_account_month_unique
  on public.ceb_data (account_number, billing_month);

-- ------------------------------------------- inverter_data_live (5-minute telemetry)
create table if not exists public.inverter_data_live (
  id bigint generated by default as identity primary key,
  inverter_sn text not null,
  data_timestamp timestamp with time zone not null,
  power_ac numeric,
  generation_today numeric,
  inverter_temp numeric,
  status integer,
  raw_data jsonb
);

create unique index if not exists inverter_data_live_unique_entry
  on public.inverter_data_live (inverter_sn, data_timestamp);

-- ------------------------------------------------- inverter_data_daily_summary
-- Aggregated from inverter_data_live, and backfillable from the Solis month API.
--
-- NOTE: peak_power_kw is nullable on purpose. It is only ever a real measurement when
-- derived from the 5-minute live series; /v1/api/inverterMonth exposes no peak field at all,
-- so rows restored by the backfill carry null (unknown) rather than 0 (a measured zero).
create table if not exists public.inverter_data_daily_summary (
  id bigint generated by default as identity primary key,
  inverter_sn text not null,
  summary_date date not null,
  total_generation_kwh numeric(10,2) not null,
  peak_power_kw numeric(10,2),
  created_at timestamp without time zone default now()
);

create unique index if not exists inverter_data_daily_summary_inverter_sn_summary_date_key
  on public.inverter_data_daily_summary (inverter_sn, summary_date);

-- ----------------------------------------------- inverter_data_monthly_summary
-- Written by scripts/backfill_monthly_summaries.js. Nothing in src/ reads it today — the
-- dashboard aggregates from the daily table instead. Kept for now; a candidate for removal.
create table if not exists public.inverter_data_monthly_summary (
  id bigint generated by default as identity primary key,
  inverter_sn text not null,
  summary_month text not null,
  total_generation_kwh numeric(12,2) not null,
  peak_power_kw numeric(10,2),
  created_at timestamp without time zone default now()
);

create unique index if not exists inverter_data_monthly_summary_inverter_sn_summary_month_key
  on public.inverter_data_monthly_summary (inverter_sn, summary_month);

-- ------------------------------------------------- inverter_data_live_archive
create table if not exists public.inverter_data_live_archive (
  inverter_sn text not null,
  data_timestamp timestamp without time zone not null,
  power_ac numeric,
  generation_today numeric,
  inverter_temp numeric,
  status integer,
  raw_data jsonb,
  created_at timestamp without time zone default now(),
  primary key (inverter_sn, data_timestamp)
);

-- ---------------------------------------------------------- system_settings
-- rate_per_kwh, solar_grid_capacity, daily_generation_target, theme.
-- Written only through the admin API (api/settings.js) with the service-role key.
create table if not exists public.system_settings (
  id bigint generated by default as identity primary key,
  setting_name text not null,
  setting_value text not null,
  description text,
  updated_at timestamp without time zone default now()
);

create unique index if not exists system_settings_setting_name_key
  on public.system_settings (setting_name);

-- ----------------------------------------------------------- system_metrics
-- Currently unused: its only writer (api/update-total-generation.js) and its only reader
-- (getTotalGenerationData in dataService) were both removed in the 2026-09 audit as dead
-- code. The single row had been stale since 2025-11-16. Kept so the schema is complete.
create table if not exists public.system_metrics (
  id bigint generated by default as identity primary key,
  metric_name text not null,
  metric_value numeric not null,
  updated_at timestamp with time zone default now()
);

create unique index if not exists system_metrics_metric_name_key
  on public.system_metrics (metric_name);

-- -------------------------------------------------------------- admin_users
-- Legacy: authorization now reads Clerk publicMetadata.role. Its only reader is
-- src/lib/auth/SupabaseAuthAdapter.js, the pre-Clerk path, dead while VITE_USE_CLERK_AUTH
-- is enabled. RLS is on with no policies, so it is unreachable via the Data API.
create table if not exists public.admin_users (
  id bigint generated by default as identity primary key,
  email text not null,
  created_at timestamp without time zone default now()
);

create unique index if not exists admin_users_email_key
  on public.admin_users (email);

-- ------------------------------------------------------------------ api_logs
create table if not exists public.api_logs (
  id bigint generated by default as identity primary key,
  endpoint text,
  response_code text,
  success boolean,
  message text,
  created_at timestamp without time zone default now()
);

-- --------------------------------------------------------------- report_logs
create table if not exists public.report_logs (
  id uuid primary key default gen_random_uuid(),
  user_id text,
  user_email text,
  report_type text not null,
  format text not null,
  status text not null default 'pending'::text,
  filters jsonb not null default '{}'::jsonb,
  generated_at timestamp with time zone not null default now(),
  download_urls jsonb,
  size_bytes bigint,
  metadata jsonb,
  error_message text
);

create index if not exists idx_report_logs_generated_at
  on public.report_logs (generated_at desc);

create index if not exists idx_report_logs_type_status
  on public.report_logs (report_type, status);

-- ============================================================================
-- RLS
-- ============================================================================
-- Every table above has RLS enabled. `api_logs` and `report_logs` intentionally have no
-- policies at all — they are written by the service role only and are not meant to be
-- reachable through the Data API. Supabase's advisor reports that as
-- "RLS Enabled No Policy"; it is deliberate, and this comment is the record of that.
alter table public.ceb_data                      enable row level security;
alter table public.inverter_data_live            enable row level security;
alter table public.inverter_data_daily_summary   enable row level security;
alter table public.inverter_data_monthly_summary enable row level security;
alter table public.inverter_data_live_archive    enable row level security;
alter table public.system_settings               enable row level security;
alter table public.system_metrics                enable row level security;
alter table public.admin_users                   enable row level security;
alter table public.api_logs                      enable row level security;
alter table public.report_logs                   enable row level security;
